### ISSUE TITLE
Add test case utility for e.g. console width

### ISSUE THREAD

**Issue by MarkusH** [adamchainz/django-rich#36]
### Description

While writing a test for a `RichCommand` management command, I ran into trouble on the CI, because inside a Rich Table, the column headers were cropped from `Maximum Value` to `Max…`.

First, I couldn't reproduce this locally, since my console width was at about 300 characters. On the CI, however, it as just 80 chars.

I now have a mixin for my test cases that allows me to set some console configurations:

```python
from contextlib import contextmanager
from functools import partial
from unittest import mock
from rich.console import Console

class RichConsoleMixin:
    @contextmanager
    def patch_console(self):
        with mock.patch(
            "django_rich.management.RichCommand.make_rich_console",
            partial(Console, width=200),
        ):
            yield
```

Usage:

```python
class TestMyCommand(RichConsoleMixin, TestCase):
    def test_call(self):
        stdout = io.StringIO()
        with self.patch_console():
            call_command("my_command", stdout=stdout)
        out = stdout.getvalue()
        self.assertIn("Maximum Value", out)
```

It might be convenient to have a similar mixin available as part of rich-django.

**Comment by adamchainz** [comment]
You could also enforce a minimum width in your command, like:

```python
from rich.console import Console


class RichCommand(BaseCommand):
    def make_rich_console(self, *args, **kwargs):
        console = Console(*args, **kwargs)
        if console.width < 200:
            console.width = 200
        return console
```

Maybe that would be preferable to patching at test time, since it sounds like you'd want that minimum width even when running interactively?

Or you could also [override the env var]https://adamj.eu/tech/2020/10/13/how-to-mock-environment-variables-with-pythons-unittest/) `COLUMNS` globally during tests, as I just added a note about [for the test runner](https://github.com/adamchainz/django-rich#output-width-on-ci).

**Comment by adamchainz** [comment]
I think we’ll just go with the note for now (added in #38).
